export const homeObj1 = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: '../../images/car.svg', 
    alt: 'Car', 
    dark: true,
    primary: true, 
    darkText: false,
} 

export const homeObj2 = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a smart-phone or a computer.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: '../../images/pigbank.svg', 
    alt: 'Piggybank', 
    dark: false,
    primary: false, 
    darkText: true,
} 

export const homeObj3 = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headline: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and you\'re ready to go.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: '../../images/securedata.svg', 
    alt: 'Car', 
    dark: true,
    primary: true, 
    darkText: false,
} 